name: Smarthome4u
version: "0.2.1"
slug: smarthome4u
description: >-
  Jednoduché rozhraní pro Home Assistant. Dashboard se vytvoří sám
  z místností a zařízení.
url: "https://github.com/Paulee196/Smarthome4u-HA"
arch:
  - amd64
  - aarch64
init: false
boot: auto
startup: application
ingress: true
ingress_port: 8099
panel_title: Smarthome4u
panel_icon: mdi:home-lightbulb
homeassistant_api: true
apparmor: true
options: {}
schema: {}
